export const restaurants = [
  {
    name: 'Gama Express - San Bernardino',
    rating: '5 Excellent',
    ratings: '(500+)',
    distance: '0.7 miles away',
    logo: require('./imagenes/logo.png'),
    img: require('./imagenes/r1.jpeg'),
    tags: [],
    duration: '35 - 45',
  },
  {
    name: 'Pan de Tata',
    rating: '4.8 Excellent',
    ratings: '(500+)',
    distance: '0.7 miles away',
    logo: require('./imagenes/logo2.png'),
    img: require('./imagenes/r2.jpeg'),
    tags: [],
    duration: '35 - 45',
  },
  {
    name: 'Gama Express',
    rating: '4.5 Excellent',
    ratings: '(500+)',
    distance: '0.7 miles away',
    logo: require('./imagenes/logo.png'),
    img: require('./imagenes/r1.jpeg'),
    tags: [],
    duration: '35 - 45',
  },
  {
    name: 'Pan de Tata',
    rating: '4.8 Excellent',
    ratings: '(500+)',
    distance: '0.7 miles away',
    logo: require('./imagenes/logo2.png'),
    img: require('./imagenes/r2.jpeg'),
    tags: [],
    duration: '35 - 45',
  },
];
