export interface Country {
  name: string;
  dial_code: string;
  code: string;
  flag: string;
  phoneLength: number;
}

export const countries: Country[] = [
  {
    name: 'Albania',
    dial_code: '+355',
    code: 'AL',
    flag: 'https://flagsapi.com/AL/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Alemania',
    dial_code: '+49',
    code: 'DE',
    flag: 'https://flagsapi.com/DE/flat/64.png',
    phoneLength: 11,
  },
  {
    name: 'Andorra',
    dial_code: '+376',
    code: 'AD',
    flag: 'https://flagsapi.com/AD/flat/64.png',
    phoneLength: 6,
  },
  {
    name: 'Argentina',
    dial_code: '+54',
    code: 'AR',
    flag: 'https://flagsapi.com/AR/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Austria',
    dial_code: '+43',
    code: 'AT',
    flag: 'https://flagsapi.com/AT/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Bélgica',
    dial_code: '+32',
    code: 'BE',
    flag: 'https://flagsapi.com/BE/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Bielorrusia',
    dial_code: '+375',
    code: 'BY',
    flag: 'https://flagsapi.com/BY/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Bolivia',
    dial_code: '+591',
    code: 'BO',
    flag: 'https://flagsapi.com/BO/flat/64.png',
    phoneLength: 8,
  },
  {
    name: 'Brasil',
    dial_code: '+55',
    code: 'BR',
    flag: 'https://flagsapi.com/BR/flat/64.png',
    phoneLength: 11,
  },
  {
    name: 'Bulgaria',
    dial_code: '+359',
    code: 'BG',
    flag: 'https://flagsapi.com/BG/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Chile',
    dial_code: '+56',
    code: 'CL',
    flag: 'https://flagsapi.com/CL/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Colombia',
    dial_code: '+57',
    code: 'CO',
    flag: 'https://flagsapi.com/CO/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Costa Rica',
    dial_code: '+506',
    code: 'CR',
    flag: 'https://flagsapi.com/CR/flat/64.png',
    phoneLength: 8,
  },
  {
    name: 'Croacia',
    dial_code: '+385',
    code: 'HR',
    flag: 'https://flagsapi.com/HR/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Cuba',
    dial_code: '+53',
    code: 'CU',
    flag: 'https://flagsapi.com/CU/flat/64.png',
    phoneLength: 8,
  },
  {
    name: 'Dinamarca',
    dial_code: '+45',
    code: 'DK',
    flag: 'https://flagsapi.com/DK/flat/64.png',
    phoneLength: 8,
  },
  {
    name: 'Ecuador',
    dial_code: '+593',
    code: 'EC',
    flag: 'https://flagsapi.com/EC/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'El Salvador',
    dial_code: '+503',
    code: 'SV',
    flag: 'https://flagsapi.com/SV/flat/64.png',
    phoneLength: 8,
  },
  {
    name: 'Eslovaquia',
    dial_code: '+421',
    code: 'SK',
    flag: 'https://flagsapi.com/SK/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Eslovenia',
    dial_code: '+386',
    code: 'SI',
    flag: 'https://flagsapi.com/SI/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'España',
    dial_code: '+34',
    code: 'ES',
    flag: 'https://flagsapi.com/ES/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Estonia',
    dial_code: '+372',
    code: 'EE',
    flag: 'https://flagsapi.com/EE/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Finlandia',
    dial_code: '+358',
    code: 'FI',
    flag: 'https://flagsapi.com/FI/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Francia',
    dial_code: '+33',
    code: 'FR',
    flag: 'https://flagsapi.com/FR/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Grecia',
    dial_code: '+30',
    code: 'GR',
    flag: 'https://flagsapi.com/GR/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Guatemala',
    dial_code: '+502',
    code: 'GT',
    flag: 'https://flagsapi.com/GT/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Hungría',
    dial_code: '+36',
    code: 'HU',
    flag: 'https://flagsapi.com/HU/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Irlanda',
    dial_code: '+353',
    code: 'IE',
    flag: 'https://flagsapi.com/IE/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Islandia',
    dial_code: '+354',
    code: 'IS',
    flag: 'https://flagsapi.com/IS/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Italia',
    dial_code: '+39',
    code: 'IT',
    flag: 'https://flagsapi.com/IT/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Letonia',
    dial_code: '+371',
    code: 'LV',
    flag: 'https://flagsapi.com/LV/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Lituania',
    dial_code: '+370',
    code: 'LT',
    flag: 'https://flagsapi.com/LT/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Luxemburgo',
    dial_code: '+352',
    code: 'LU',
    flag: 'https://flagsapi.com/LU/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Malta',
    dial_code: '+356',
    code: 'MT',
    flag: 'https://flagsapi.com/MT/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'México',
    dial_code: '+52',
    code: 'MX',
    flag: 'https://flagsapi.com/MX/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Mónaco',
    dial_code: '+377',
    code: 'MC',
    flag: 'https://flagsapi.com/MC/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Noruega',
    dial_code: '+47',
    code: 'NO',
    flag: 'https://flagsapi.com/NO/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Países Bajos',
    dial_code: '+31',
    code: 'NL',
    flag: 'https://flagsapi.com/NL/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Panamá',
    dial_code: '+507',
    code: 'PA',
    flag: 'https://flagsapi.com/PA/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Paraguay',
    dial_code: '+595',
    code: 'PY',
    flag: 'https://flagsapi.com/PY/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Perú',
    dial_code: '+51',
    code: 'PE',
    flag: 'https://flagsapi.com/PE/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Polonia',
    dial_code: '+48',
    code: 'PL',
    flag: 'https://flagsapi.com/PL/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Portugal',
    dial_code: '+351',
    code: 'PT',
    flag: 'https://flagsapi.com/PT/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Reino Unido',
    dial_code: '+44',
    code: 'GB',
    flag: 'https://flagsapi.com/GB/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'República Checa',
    dial_code: '+420',
    code: 'CZ',
    flag: 'https://flagsapi.com/CZ/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'República Dominicana',
    dial_code: '+1',
    code: 'DO',
    flag: 'https://flagsapi.com/DO/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Rumania',
    dial_code: '+40',
    code: 'RO',
    flag: 'https://flagsapi.com/RO/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Rusia',
    dial_code: '+7',
    code: 'RU',
    flag: 'https://flagsapi.com/RU/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Serbia',
    dial_code: '+381',
    code: 'RS',
    flag: 'https://flagsapi.com/RS/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Suecia',
    dial_code: '+46',
    code: 'SE',
    flag: 'https://flagsapi.com/SE/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Suiza',
    dial_code: '+41',
    code: 'CH',
    flag: 'https://flagsapi.com/CH/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Ucrania',
    dial_code: '+380',
    code: 'UA',
    flag: 'https://flagsapi.com/UA/flat/64.png',
    phoneLength: 10,
  },
  {
    name: 'Uruguay',
    dial_code: '+598',
    code: 'UY',
    flag: 'https://flagsapi.com/UY/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Vaticano',
    dial_code: '+379',
    code: 'VA',
    flag: 'https://flagsapi.com/VA/flat/64.png',
    phoneLength: 9,
  },
  {
    name: 'Venezuela',
    dial_code: '+58',
    code: 'VE',
    flag: 'https://flagsapi.com/VE/flat/64.png',
    phoneLength: 10,
  },
];
